;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname |Ex 20|) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ())))
(require 2htdp/image)
(above (circle 10 "outline" "red")
       (beside (rectangle 10 10 "solid" "blue")
               (rectangle 10 20 "solid" "blue")
               (rectangle 10 20 "solid" "blue")
               (rectangle 10 20 "solid" "blue")
               (rectangle 10 10 "solid" "blue")
        )
       (beside (rectangle 10 20 "solid" "blue")
               (rectangle 10 20 "solid" "blue")
               (rectangle 10 20 "solid" "blue")
        )
       (beside (rectangle 10 20 "solid" "blue")
               (rectangle 10 20 "solid" "white")
               (rectangle 10 20 "solid" "blue")
        )
)

